version: "2"
volumes:
  screeps-grafana_vm_data:
    external: true
  screeps-grafana_grafana_data:
    external: true
services:
  node:
    build:
        context: .
        dockerfile: Dockerfile
    restart: always
    links:
     - statsd
    environment:
     GRAPHITE_PORT_8125_UDP_ADDR: "statsd"
    env_file: docker-compose.env
  statsd:
    image: statsd/statsd
    restart: always
    links:
     - victoriametrics
    ports:
     - "8125:8125/udp"
    volumes:
     - ./statsd.config.js:/usr/src/app/config.js
  victoriametrics:
    image: victoriametrics/victoria-metrics:latest
    restart: always
    command:
      - --retentionPeriod=12
      - --graphiteListenAddr=:2003
      - --storageDataPath=/storage
    ports:
      - "8428:8428"
    volumes:
     - screeps-grafana_vm_data:/storage
  grafana:
    image: grafana/grafana
    restart: always
    volumes:
     - screeps-grafana_grafana_data:/var/lib/grafana
    links:
     - victoriametrics
    ports:
     - "1337:3000"
